### ISSUE TITLE
NullPointer at getId

### ISSUE THREAD

**Issue by SandroCoutinho** [Parabot/Parabot-317-API-Minified-Dreamscape#1]
```
java.lang.NullPointerException
    at org.rev317.min.api.wrappers.NpcDef.getId(NpcDef.java:42)
    at org.rev317.min.api.wrappers.NpcDef.getId(NpcDef.java:21)
    at org.emmastone.parabot.scripts.dreamscape.shadowking.strategies.Attack.lambda$activate$0(Attack.java:16)
    at org.rev317.min.api.methods.Npcs.getNpcs(Npcs.java:54)
    at org.rev317.min.api.methods.Npcs.getNearest(Npcs.java:111)
    at org.emmastone.parabot.scripts.dreamscape.shadowking.strategies.Attack.activate(Attack.java:16)
    at org.parabot.environment.scripts.framework.StrategyWorker.execute(Frameworks.java:55)
    at org.parabot.environment.scripts.Script.run(Script.java:113)
    at java.lang.Thread.run(Thread.java:748)

**Comment by JKetelaar** [comment]
Could you provide the code you're using to reproduce this error?

**Comment by SandroCoutinho** [comment]
```
import org.rev317.min.api.methods.Npcs;

public class Attack implements org.parabot.environment.scripts.framework.Strategy {

    @Override
    public boolean activate() {
        Npcs.getNearest(npc -> npc.getDef().getId() == Constants.SHADOWKING_ID)

        return false;
    }

    @Override
    public void execute() { }
}
```

**Comment by JKetelaar** [comment]
_FYI: Updated your code to only provide code regarding the error._

**Comment by JKetelaar** [comment]
What is the desc value of the id field of `NpcDef` in the client?

**Comment by SandroCoutinho** [comment]
`long`

**Comment by SandroCoutinho** [comment]
A way to fix this issue is to surround `Npc.getNearest` with a try/catch
Example
```
            try {
                Npc[] npcs = Npcs.getNearest(new Filter<Npc>() {
                    @Override
                    public boolean accept(Npc npc) {
                        return npc.getDef().getId() == Constants.AUBURY_ID;
                    }
                });
            } catch (NullPointerException ignored) {
            }
